### ISSUE TITLE
Minor changes to improve your project!

### ISSUE THREAD

**Issue by orozCoding** [AkshithaReddy1899/Capstone-1-HTML-CSS#2]
Great work this far with your project! I believe is almost ready to submit it!

I'd suggest you do some minor improvements to match even more with the template we were given. For example:

- Change the colors in the header/headline. You could use a little bit more orange!
- Center the text in the first section on the about page
- On the same page, move the logo to the bottom of the logo description section.

Good luck! ❤️

**Comment by HAMMAS-SALEEM** [comment]
👍 Great work on Project so far. I can see your hard work on the project and I really impressed by your work. ✔️ 

I think I have nothing to say but an optional suggestion. 

- [ ] Can you include a screenshot of your web application to your README.MD file.

**Comment by AkshithaReddy1899** [comment]
Thank you for your kind words, I will implement the changes as soon as possible
